const EVENTS = {
  TODO_LIST: {
    CATEGORY: {
      CHANGE: "CHANGE",
      INBOX: {
        ADD_SECTION: "CHANGE.INBOX.ADD_SECTION"
      },
      MY_PROJECT: {
        ADD_CATEGORY: "CHANGE.MY_PROJECT.ADD_CATEGORY",
        ADD_SECTION: "CHANGE.MY_PROJECT.ADD_SECTION"
      },
      ADD: "CHANGE.ADD_CATEGORY",
      MARK: "CHANGE.MARK_CATEGORY",
      EDIT: "CHANGE.EDIT_CATEGORY",
      GET_TASK: "GET_TASK",
      TASK_SENT: "TASK_SENT",
      SEND_LABEL: "SEND_LABEL",
      LABEL_SENT: "LABEL_SENT",
      DISPLAY_ALL: "DISPLAY_ALL_CATEGORY",
      DISPLAY_FILTER: "DISPLAY_FILTER_TASK",
      DELETE: "CHANGE.DELETE_CATEGORY",
      REFERENCE: "CATEGORY_REFERENCE",
    }
  },
  PAGE: {
    LOAD: {
      HERO: "LOAD.HERO_PAGE",
      TODAY: "LOAD.TODAY_PAGE",
      SEARCH: "LOAD.SEARCH_PAGE",
      CATEGORY: "LOAD.TODAY_PAGE",
      MAIN_NAV_CONTROLLER: "LOAD.MAIN_NAV_CONTROLLER_PAGE"
    },
    REMOVE: {
      HERO: "REMOVE_HERO_PAGE",
      TODAY: "REMOVE_TODAY_PAGE"
    }
  }
};

export default EVENTS;
