const EVENTS = {
  TODO_LIST: {
    CATEGORY: {
      CHANGE: "CHANGE",
      INBOX: {
        ADD_SECTION: "CHANGE.INBOX.ADD_SECTION"
      },
      MY_PROJECT: {
        ADD_CATEGORY: "CHANGE.MY_PROJECT.ADD_CATEGORY",
        ADD_SECTION: "CHANGE.MY_PROJECT.ADD_SECTION"
      },
      ADD: "CHANGE.ADD_CATEGORY",
      MARK: "CHANGE.MARK_CATEGORY",
      EDIT: "CHANGE.EDIT_CATEGORY",
      VIEW_TASK_DIALOG: "VIEW_TASK_DIALOG",
      ADD_TASK_DIALOG: "ADD_TASK_DIALOG",
      TASK_SENT: "TASK_SENT",
      SEND_LABEL: "SEND_LABEL",
      LABEL_SENT: "LABEL_SENT",
      DISPLAY_ALL: "DISPLAY_ALL_CATEGORY",
      DISPLAY_FILTER: "DISPLAY_FILTER_TASK",
      DELETE: "CHANGE.DELETE_CATEGORY",
      REFERENCE: "CATEGORY_REFERENCE"
    }
  },
  UI: {
    MARK: "TASK_MARK"
  },
  PAGE: {
    LOAD: {
      HERO: "LOAD.HERO_PAGE",
      TODAY: "LOAD.TODAY_PAGE",
      SEARCH: "LOAD.SEARCH_PAGE",
      CATEGORY: "LOAD.CATEGORY_PAGE",
      SUBSECTION: "LOAD.CATEGORY_SUBSECTION_PAGE",
      PREVIOUS_PAGE: "LOAD.PREVIOUS_PAGE",
      INBOX: "LOAD.INBOX",
      MY_PROJECT: "LOAD.MY_PROJECT",
      MY_PROJECT_SUBSECTION: "LOAD.MY_PROJECT_SUBSECTION",
      MAIN_NAV_CONTROLLER: "MAIN_NAV_CONTROLLER_PAGE"
    },
    CHANGE: "LOAD",
    REMOVE: {
      HERO: "REMOVE_HERO_PAGE",
      TODAY: "REMOVE_TODAY_PAGE",
      TASK_DIALOG: "REMOVE_TASK_DIALOG"
    }
  }
};

export default EVENTS;
