const EVENTS = {
  TODO_LIST: {
    TASK_STORE: {
      CHANGE: "TASK_STORE.CHANGE",
      FILTER_BY: "TASK_STORE.FILTER_BY",
      ADD: "TASK_STORE.CHANGE.ADD_TASK",
      MARK_STATUS: "TASK_STORE.CHANGE.MARK_TASK_STATUS",
      EDIT: "TASK_STORE.CHANGE.EDIT_TASK",
      DELETE: "TASK_STORE.CHANGE.DELETE_TASK"
    },
    TASK_INDEXES_STORE: {
      CHANGE: "TASK_INDEXES_STORE.CHANGE",
      ADD: "TASK_INDEXES_STORE.CHANGE.ADD_TASK_INDEX"
    },
    CATEGORY: {
      CHANGE: "CHANGE",
      INBOX: {
        ADD_SECTION: "CHANGE.INBOX.ADD_SECTION"
      },
      MY_PROJECT: {
        ADD_CATEGORY: "CHANGE.MY_PROJECT.ADD_CATEGORY",
        ADD_SECTION: "CHANGE.MY_PROJECT.ADD_SECTION"
      },
      CATEGORIZE: "CHANGE.CATEGORIZE TASK BASE ON IT CATEGORY"
    }
  },
  PAGE: {
    LOAD: {
      HERO: "LOAD.HERO_PAGE",
      TODAY: "LOAD.TODAY_PAGE",
      MAIN_NAV_CONTROLLER: "LOAD.MAIN_NAV_CONTROLLER_PAGE"
    },
    REMOVE: {
      HERO: "REMOVE_HERO_PAGE",
      TODAY: "REMOVE_TODAY_PAGE"
    }
  }
};

export default EVENTS;
