const EVENTS = {
  STORE: {
    TASK_STORE: {
      CHANGE: "TASK_STORE.CHANGE",
      ADD: "TASK_STORE.CHANGE.ADD_TASK",
      DELETE: "TASK_STORE.CHANGE.DELETE_TASK",
      MARK_STATUS: "TASK_STORE.CHANGE.MARK_TASK_STATUS"
    },
    TASK_INDEXES_STORE: {
      CHANGE: "TASK_INDEXES_STORE.CHANGE",
      ADD: "TASK_INDEXES_STORE.CHANGE.ADD_TASK_INDEX"
    }
  }
};

export default EVENTS;
