const EVENTS = {
  NAV_RERENDER: "NAV_RERENDER",
  NAV_RENDER: "NAV_RENDER",
  
  SHOW_TASK_DIALOG: "SHOW_TASK_DIALOG",

  // Nav (Pages)
  TODAY: "TODAY",
  SEARCH: "SEARCH",
  CATEGORY: "CATEGORY",
  SUBCATEGORY: "SUBCATEGORY"
};

export default EVENTS;
